export { default as HomeIcon } from './nav-home-unselected-shadow.svg';
export { default as HomeActiveIcon } from './nav-home-selected-shadow.svg';
export { default as DiscoverIcon } from './nav-discover-unselected-shadow.svg';
export { default as DiscoverActiveIcon } from './nav-discover-selected-shadow.svg';
export { default as CoachesIcon } from './nav-coaches-unselected-shadow.svg';
export { default as CoachesActiveIcon } from './nav-coaches-selected-shadow.svg';
export { default as PlatformsIcon } from './nav-platforms-unselected-shadow.svg';
export { default as PlatformsActiveIcon } from './nav-platforms-selected-shadow.svg';
export { default as NavLinkBackgroundIcon } from './nav-background.svg';
